#sql server connection
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=MS_DB_USER;encrypt=false
    username: sa
    password: UltraSecret@2121
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

#server port
server:
  port: 9090